openapi: 3.0.0
info:
  title: Urdu Translation API
  description: API for translating textbook content to Urdu with bonus points system
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
  - url: https://staging-api.example.com
    description: Staging server

paths:
  /api/translate:
    post:
      summary: Translate content to Urdu
      description: Translates provided content to Urdu and awards bonus points to authenticated user
      operationId: translateContent
      tags:
        - Translation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateRequest'
      responses:
        '200':
          description: Successfully translated content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslateResponse'
        '400':
          description: Bad request - invalid content or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - insufficient account verification level
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limited - too many translation requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/user/points:
    get:
      summary: Get user bonus points
      description: Retrieves the user's bonus points and history
      operationId: getUserPoints
      tags:
        - Points
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user points
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointsResponse'
        '401':
          description: Unauthorized - user not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TranslateRequest:
      type: object
      required:
        - content
        - chapter_id
      properties:
        content:
          type: string
          description: The content to be translated to Urdu
          example: "Physical AI combines robotics and artificial intelligence to create systems that interact with the physical world."
        chapter_id:
          type: string
          description: The identifier of the chapter containing the content
          example: "physical-ai-introduction"
        target_language:
          type: string
          description: Target language code (default is 'ur' for Urdu)
          default: "ur"
          example: "ur"

    TranslateResponse:
      type: object
      required:
        - translated_content
        - session_id
        - bonus_points_awarded
        - total_points
      properties:
        translated_content:
          type: string
          description: The translated content in Urdu
          example: "فزکل AI روبوٹکس اور مصنوعی ذہانت کو جوڑتا ہے تاکہ وہ جسمانی دنیا کے ساتھ تعامل کرنے والے سسٹم تیار کیے جا سکیں۔"
        session_id:
          type: string
          description: Unique identifier for this translation session
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        bonus_points_awarded:
          type: integer
          description: Number of bonus points awarded for this translation
          example: 50
        total_points:
          type: integer
          description: User's total bonus points after this translation
          example: 150
        is_cached:
          type: boolean
          description: Whether the translation was retrieved from cache
          example: false

    PointsResponse:
      type: object
      required:
        - total_points
        - points_history
      properties:
        total_points:
          type: integer
          description: User's total bonus points
          example: 150
        points_history:
          type: array
          items:
            $ref: '#/components/schemas/PointsRecord'
          description: History of bonus points earned

    PointsRecord:
      type: object
      required:
        - chapter_id
        - points
        - earned_at
      properties:
        chapter_id:
          type: string
          description: The chapter where points were earned
          example: "physical-ai-introduction"
        points:
          type: integer
          description: Number of points earned
          example: 50
        earned_at:
          type: string
          format: date-time
          description: When the points were earned
          example: "2025-12-15T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "TRANSLATION_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Translation service unavailable"
        details:
          type: object
          description: Additional error details (optional)
          example: {"retry_after": 3600}